export const featuredMovies = [
	{
		imdbID: '1',
		Title: 'The Exorcist',
		Year: '1973',
		Type: 'Movie',
		Poster: '/assets/TheExorcist.jpg',
		Production: 'Warner Brothers, Hoya Productions',
		Genre: 'Horror',
		Language: 'English,Latin,Greek,French,German,Arabic,Kurdish',
		Country: 'United States',
		Rated: 'R',
		Awards: 'Won 2 Oscars. 16 wins & 17 nominations total',
		BoxOffice: '$232,906,145',
		Director: 'William Friedkin',
		Actors: 'Ellen Burstyn, Max von Sydow, Linda Blair',
		Plot: 'When a 12-year-old girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her.',
		Ratings: [
			{ Source: 'Internet Movie Database:', Value: '8/10' },
			{ Source: 'Rotten Tomatoes:', Value: '83%' },
			{ Source: 'Metacritic:', Value: '81/100' },
		],
	},
	{
		imdbID: '2',
		Title: 'The Wire',
		Year: '2002',
		Type: 'Series',
		Poster: '/assets/theWire.png',
		Production: 'N/A',
		Genre: 'Crime,Drama,Thriller',
		Language: 'English,Greek,Mandarin,Spanish',
		Country: 'USA',
		Rated: 'TV-MA',
		Awards: 'Nominated for 2 Primetime Emmys. Another 16 wins & 52 nominations',
		BoxOffice: 'N/A',
		Actors: 'Dominic West, John Doman, Deirdre Lovejoy, Wendell Pierce',
		Director: 'N/A',
		Plot: 'The Baltimore drug scene, as seen through the eyes of drug dealers and law enforcement.',
		Ratings: [ { Source: 'internet Movie Database:', Value: '9.3/10' } ],
	},
	{
		imdbID: '3',
		Title: 'Troy',
		Year: '2004',
		Type: 'Movie',
		Poster: '/assets/Troy.jpg',
		Production: 'Plang B Films, Radiant Pictures, Village Roadshow Prod., Warner Brothers',
		Genre: 'Drama,History',
		Language: 'English',
		Country: 'USA,Malta,UK',
		Rated: 'R',
		Awards: 'Nominated for 1 Oscar. Another 5 wins & 22 nominations',
		BoxOffice: '$133.378.256',
		Director: 'Wolfgang Petersen',
		Actors: 'Julian Glover,Brian Cox, Nathan Jones, Adoni Maropis',
		Plot:
			"An adaptation of Homer's great epic, the film follows the assault on Troy by the united Greek forces and chronicles the fates of the men involved.",
		Ratings: [
			{ Source: 'Internet Movie Database:', Value: '7.2/10' },
			{ Source: 'Rotten Tomatoes:', Value: '54%' },
			{ Source: 'Metacritic:', Value: '56/100' },
		],
	},
	{
		imdbID: '4',
		Title: 'Kingdom of Heaven',
		Year: '2005',
		Type: 'Movie',
		Poster: '/assets/KingdomOfHeaven.jpg',
		Production: 'Scott Free Productions',
		Genre: 'Action, Adventure, Drama, History, War',
		Country: 'UK, Germany, Spain, Morocco, USA, Italy, France',
		Rated: 'R',
		Awards: '5 wins & 15 nominations',
		BoxOffice: '$47.398.413',
		Director: 'Ridley Scott',
		Actors: 'Martin Hancock, Michael Sheen, Nathalie Cox, Eriq Elbouaney',
		Plot:
			'Balian of Ibelin travels to Jerusalem during the Crusades of the 12th century, and there he finds himself as the defender of the city and its people.',
		Ratings: [
			{ Source: 'Internet Movie Database:', Value: '7.2/10' },
			{ Source: 'Rotten Tomatoes:', Value: '39%' },
			{ Source: 'Metacritic:', Value: '63/100' },
		],
	},
	{
		imdbID: '5',
		Title: 'Interstellar',
		Year: '2014',
		Type: 'Movie',
		Poster: '/assets/Interstellar.png',
		Production: 'Lynda Obst Productions, Syncopy',
		Genre: 'Adventure, Drama, Sci-Fi',
		Language: 'English',
		Rated: 'PG-13',
		Awards: 'Won 1 Oscar. Another 43 wins & 148 nominations.',
		BoxOffice: '188.020.017',
		Director: 'Christopher Nolan',
		Actors: 'Ellen Burstyn, Matthew McConaughey, Mackenzie Foy, John Lithgow',
		Plot: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
		Ratings: [
			{ Source: 'Internet Movie Database:', Value: '8.6/10' },
			{ Source: 'Rotten Tomatoes:', Value: '72%' },
			{ Source: 'Metacritic:', Value: '74/100' },
		],
	},
];

export const defaultImg = 'assets/no_poster.png';
